name: Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: restore-dependencies
        run: dotnet restore --verbosity minimal

      - name: build
        run: dotnet build --no-restore --verbosity minimal

      - name: test
        run: dotnet test --no-build --verbosity minimal
